package com.wellnessapp.model.mood;

import com.wellnessapp.enums.MoodType;
import com.wellnessapp.model.DatabaseConnection;
import com.wellnessapp.model.mood.IMoodDAO;
import com.wellnessapp.model.mood.MoodEntry;

import java.sql.*;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class MoodDAO implements IMoodDAO {
    public final Connection connection;
    public MoodDAO() {
        connection = DatabaseConnection.getInstance();
        createTable();
    }
    private void createTable() {
        try {
            connection.createStatement().execute(
                    "CREATE TABLE IF NOT EXISTS moods ("
                            + "id INTEGER PRIMARY KEY AUTOINCREMENT,"
                            + "timestamp Timestamp NOT NULL,"
                            + "mood VARCHAR NOT NULL,"
                            + "comment VARCHAR"
                            + ")"
            );
        } catch(SQLException exception) {
            exception.printStackTrace();
        }
    }

    /**
     * Inserts a new {@link MoodEntry} into the database.
     * <br><br>
     * Upon successful insertion, the ID generated by the database will be set back to the provided {@code MoodEntry} object.
     * @param entry the {@link MoodEntry} object containing the mood details to be inserted into the database.
     *              This object must not be {@code null}.
     * @throws SQLException Any issues executing is caught within the method and the stack trace will be printed.
     */
    @Override
    public void Create(MoodEntry entry) throws SQLException {
        try {
            PreparedStatement statement = connection.prepareStatement("INSERT INTO moods (mood, timestamp, comment) VALUES (?, ?, ?)");
            statement.setString(1, entry.getMood().toString().toUpperCase());
            statement.setTimestamp(2, Timestamp.valueOf(entry.getTimestamp()));
            statement.setString(3, entry.getComment());
            statement.executeUpdate();
            ResultSet generatedKeys = statement.getGeneratedKeys();
            if (generatedKeys.next()) {
                entry.setId(generatedKeys.getInt(1));
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }

    @Override
    public void Delete(MoodEntry entry) {

    }

    @Override
    public MoodEntry getEntryById(int id) {
        try {
            PreparedStatement statement = connection.prepareStatement("SELECT * FROM moods WHERE id = ?");
            statement.setInt(1, id);
            ResultSet r = statement.executeQuery();
            if (r.next()) {
                int entryId = r.getInt("id");
                MoodType mood = MoodType.valueOf(r.getString("mood"));
                LocalDateTime dateTime = r.getTimestamp("timestamp").toLocalDateTime();
                String comment = r.getString("comment");

                MoodEntry entry = new MoodEntry(mood, dateTime, comment);
                entry.setId(entryId);
                return entry;
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        return null;
    }

    @Override
    public List<MoodEntry> getAllEntries() {
        List<MoodEntry> entries = new ArrayList<>();
        try {
            ResultSet r = connection.createStatement().executeQuery("SELECT * FROM moods ORDER BY timestamp");
            while (r.next()) {
                int id = r.getInt("id");
                MoodType mood = MoodType.valueOf(r.getString("mood"));
                LocalDateTime dateTime = r.getTimestamp("timestamp").toLocalDateTime();
                String comment = r.getString("comment");

                final MoodEntry entry = new MoodEntry(mood, dateTime, comment);
                entry.setId(id);
                entries.add(entry);
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        return entries;
    }
}
