package com.wellnessapp.model.mood;

import com.wellnessapp.enums.MoodType;
import com.wellnessapp.model.DatabaseConnection;
import com.wellnessapp.services.AuthService;
import java.sql.*;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

/**
 * Implementation of the Mood Database Access Object (DAO) interface.
 * Provides methods to interact with mood entries stored in the database.
 */
public class MoodDAO implements IMoodDAO {
    public final Connection connection;
    /**
     * Constructs a MoodDAO object and initializes the database connection.
     */
    public MoodDAO() {
        connection = DatabaseConnection.getInstance();
        createTable();
    }
    private void createTable() {
        try {
            connection.createStatement().execute(
                    "CREATE TABLE IF NOT EXISTS moods ("
                            + "id INTEGER PRIMARY KEY AUTOINCREMENT,"
                            + "timestamp Timestamp NOT NULL,"
                            + "mood VARCHAR NOT NULL,"
                            + "comment VARCHAR,"
                            + "user_email VARCHAR,"
                            + "FOREIGN KEY (user_email) REFERENCES users(email)"
                            + ")"
            );
        } catch(SQLException exception) {
            exception.printStackTrace();
        }
    }

    /**
     * Inserts a new {@link MoodEntry} into the database.
     * <br><br>
     * Upon successful insertion, the ID generated by the database will be set back to the provided {@code MoodEntry} object.
     * @param entry the {@link MoodEntry} object containing the mood details to be inserted into the database.
     *              This object must not be {@code null}.
     * @throws SQLException Any issues executing is caught within the method and the stack trace will be printed.
     */
    @Override
    public void Create(MoodEntry entry) throws SQLException {
        try {
            PreparedStatement statement = connection.prepareStatement("INSERT INTO moods (mood, timestamp, comment, user_email) VALUES (?, ?, ?, ?)");
            statement.setString(1, entry.getMood().toString().toUpperCase());
            statement.setTimestamp(2, Timestamp.valueOf(entry.getTimestamp()));
            statement.setString(3, entry.getComment());
            statement.setString(4, AuthService.getInstance().getCurrentUser().getEmail());
            statement.executeUpdate();
            ResultSet generatedKeys = statement.getGeneratedKeys();
            if (generatedKeys.next()) {
                entry.setId(generatedKeys.getInt(1));
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }

    /**
     * Deletes a mood entry from the database.
     * @param entry The mood entry to delete.
     */
    @Override
    public void Delete(MoodEntry entry) {
        try {
            PreparedStatement statement = connection.prepareStatement("DELETE FROM moods WHERE id = ?");
            statement.setInt(1, entry.getId());
            statement.executeUpdate();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    /**
     * Updates an existing mood entry in the database.
     * @param entry The mood entry to update.
     */
    @Override
    public void Update(MoodEntry entry) {
        try {
            PreparedStatement statement = connection.prepareStatement("UPDATE moods SET mood = ?, timestamp = ?, comment = ? WHERE id = ?");
            statement.setString(1, entry.getMood().toString().toUpperCase());
            statement.setTimestamp(2, Timestamp.valueOf(entry.getTimestamp()));
            statement.setString(3, entry.getComment());
            statement.setInt(4, entry.getId());
            statement.executeUpdate();
            System.out.println("Converted mood to " + entry.getMood().toString().toUpperCase());
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    /**
     * Retrieves a mood entry from the database by its ID.
     * @param id The ID of the mood entry to retrieve.
     * @return The mood entry with the specified ID, or {@code null} if not found.
     */
    @Override
    public MoodEntry getEntryById(int id) {
        try {
            PreparedStatement statement = connection.prepareStatement("SELECT * FROM moods WHERE id = ? AND user_email = ?");
            statement.setInt(1, id);
            statement.setString(2, AuthService.getInstance().getCurrentUser().getEmail());
            ResultSet r = statement.executeQuery();
            if (r.next()) {
                int entryId = r.getInt("id");
                MoodType mood = MoodType.valueOf(r.getString("mood"));
                LocalDateTime dateTime = r.getTimestamp("timestamp").toLocalDateTime();
                String comment = r.getString("comment");

                MoodEntry entry = new MoodEntry(mood, dateTime, comment);
                entry.setId(entryId);
                return entry;
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        return null;
    }

    /**
     * Retrieves all mood entries from the database.
     * @param sorted Indicates whether the entries should be sorted, when sorted returns order by DESC, otherwise ASC
     * @return A list of mood entries.
     */
    @Override
    public List<MoodEntry> getAllEntries(boolean sorted) {
        List<MoodEntry> entries = new ArrayList<>();
        try {
            PreparedStatement statement;
            if (sorted) {
                statement = connection.prepareStatement("SELECT * FROM moods WHERE user_email = ? ORDER BY timestamp DESC");
            } else {
                statement = connection.prepareStatement("SELECT * FROM moods WHERE user_email = ? ORDER BY timestamp ASC");
            }
            statement.setString(1, AuthService.getInstance().getCurrentUser().getEmail());
            ResultSet r = statement.executeQuery();
            while (r.next()) {
                int id = r.getInt("id");
                MoodType mood = MoodType.valueOf(r.getString("mood"));
                LocalDateTime dateTime = r.getTimestamp("timestamp").toLocalDateTime();
                String comment = r.getString("comment");

                final MoodEntry entry = new MoodEntry(mood, dateTime, comment);
                entry.setId(id);
                entries.add(entry);
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        return entries;
    }
}
