name: CI/CD Pipeline Report

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B --file pom.xml --batch-mode -DskipTests package

    - name: Run Unit Tests
      run: mvn --batch-mode test

    - name: Generate Javadoc
      run: mvn javadoc:javadoc

    - name: Publish Javadoc
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: target/docs/javadoc